USE [master]
GO

CREATE LOGIN [interview] WITH PASSWORD=N'/DmCwJPzgKK444rY/zKtNLVi3pEu81LnuJlwej6tuVs=', DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=ON, CHECK_POLICY=ON
GO

ALTER LOGIN [interview] DISABLE
GO

ALTER SERVER ROLE [dbcreator] ADD MEMBER [interview]
GO
